version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/public:/var/www/html
    ports:
      - ${PORT}:80
    env_file: .env
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./app/public/sql:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306
volumes:
  mysqldata: {}
