version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: /.env
    volumes:
      - ./app:/var/www/html
    ports:
      - ${WEB_PORT}:80
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./app/public/sql:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306
volumes:
  mysqldata: {}
